services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    volumes:
      - /home/mochijj/dist/ncafe/upload:/app/upload
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db.newlecture.com:5432/ncafedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ncafe
      - SPRING_DATASOURCE_PASSWORD=new_ibm2
      - SERVER_PORT=8012
    networks:
      - ncafe-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3012:3000"
    environment:
      - BACKEND_URL=http://backend:8012
      #- PORT=3012
    depends_on:
      - backend
    networks:
      - ncafe-network

networks:
  ncafe-network:
    driver: bridge
