services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    volumes:
      - /home/mochijj/dist/ncafe/upload:/app/upload
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db.newlecture.com:5432/ncafedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ncafe
      - SPRING_DATASOURCE_PASSWORD=new_ibm2
      - SERVER_PORT=8012
    networks:
      - ncafe-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3012:3012"
    environment:
      - BACKEND_URL=http://backend:8012
      - PORT=3012
    depends_on:
      - backend
    networks:
      - ncafe-network

  # DB서비스 추가
  db:
    image: postgres:17
    profiles: [ "with-db" ]
    container_name: ${USER_ID:-ncafe}-db
    environment:
      POSTGRES_DB: ncafedb
      POSTGRES_USER: ncafe
      POSTGRES_PASSWORD: 1234
    ports:
      - "${DB_PORT:-5412}:5432"
    volumes:
      - /home/mochijj/dist/ncafe/data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  ncafe-network:
    driver: bridge