--
-- PostgreSQL database dump
--

\restrict kqNPccL76U9r4Z7hbk7YxnwIOnupR8BoZpCZbJiob4J3un0CPkriJurHGsNOFz4

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg12+1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_item_options; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.cart_item_options (
    id bigint NOT NULL,
    menu_option_id bigint,
    name character varying(255),
    price integer NOT NULL,
    value character varying(255),
    cart_item_id bigint
);


ALTER TABLE public.cart_item_options OWNER TO ncafe;

--
-- Name: cart_item_options_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.cart_item_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_item_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    base_price integer,
    cart_id character varying(255),
    menu_id bigint,
    menu_name character varying(255),
    quantity integer NOT NULL,
    total_price integer
);


ALTER TABLE public.cart_items OWNER TO ncafe;

--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    icon character varying(255),
    name character varying(255) NOT NULL,
    sort_order integer
);


ALTER TABLE public.categories OWNER TO ncafe;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inyeon_cards; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.inyeon_cards (
    id integer NOT NULL,
    user_id character varying NOT NULL,
    interests character varying[] NOT NULL,
    mood character varying NOT NULL,
    greeting character varying(100),
    is_active boolean,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.inyeon_cards OWNER TO ncafe;

--
-- Name: inyeon_cards_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

CREATE SEQUENCE public.inyeon_cards_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.inyeon_cards_id_seq OWNER TO ncafe;

--
-- Name: inyeon_cards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: ncafe
--

ALTER SEQUENCE public.inyeon_cards_id_seq OWNED BY public.inyeon_cards.id;


--
-- Name: knowledge; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.knowledge (
    id integer NOT NULL,
    content text NOT NULL,
    embedding public.vector(384)
);


ALTER TABLE public.knowledge OWNER TO ncafe;

--
-- Name: knowledge_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

CREATE SEQUENCE public.knowledge_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.knowledge_id_seq OWNER TO ncafe;

--
-- Name: knowledge_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: ncafe
--

ALTER SEQUENCE public.knowledge_id_seq OWNED BY public.knowledge.id;


--
-- Name: matches; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.matches (
    id integer NOT NULL,
    requester_id character varying NOT NULL,
    receiver_id character varying NOT NULL,
    match_score integer,
    status character varying,
    ai_message text,
    created_at timestamp without time zone,
    responded_at timestamp without time zone
);


ALTER TABLE public.matches OWNER TO ncafe;

--
-- Name: matches_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

CREATE SEQUENCE public.matches_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.matches_id_seq OWNER TO ncafe;

--
-- Name: matches_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: ncafe
--

ALTER SEQUENCE public.matches_id_seq OWNED BY public.matches.id;


--
-- Name: menu_curation_tags; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.menu_curation_tags (
    menu_id bigint NOT NULL,
    tag character varying(255)
);


ALTER TABLE public.menu_curation_tags OWNER TO ncafe;

--
-- Name: menu_images; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.menu_images (
    id bigint NOT NULL,
    alt_text character varying(255),
    menu_id bigint,
    sort_order integer,
    src_url character varying(255)
);


ALTER TABLE public.menu_images OWNER TO ncafe;

--
-- Name: menu_images_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.menu_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_option_mapping; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.menu_option_mapping (
    menu_id bigint NOT NULL,
    option_id bigint NOT NULL
);


ALTER TABLE public.menu_option_mapping OWNER TO ncafe;

--
-- Name: menu_options; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.menu_options (
    id bigint NOT NULL,
    name character varying(255),
    price integer NOT NULL,
    value character varying(255)
);


ALTER TABLE public.menu_options OWNER TO ncafe;

--
-- Name: menu_options_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.menu_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menus; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.menus (
    id bigint NOT NULL,
    admin_memo character varying(255),
    alt_text character varying(255),
    category_id integer,
    cost_price integer,
    created_at timestamp(6) without time zone,
    description character varying(255),
    eng_name character varying(255),
    is_available boolean,
    kor_name character varying(255) NOT NULL,
    price integer,
    slug character varying(255),
    updated_at timestamp(6) without time zone,
    allergy_info character varying(255),
    sort_order integer
);


ALTER TABLE public.menus OWNER TO ncafe;

--
-- Name: menus_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.menus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    menu_id bigint,
    menu_name character varying(255),
    options_text character varying(255),
    price integer NOT NULL,
    quantity integer NOT NULL,
    order_id bigint
);


ALTER TABLE public.order_items OWNER TO ncafe;

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    approval_number character varying(255),
    cart_id character varying(255),
    ordered_at timestamp(6) without time zone,
    payment_method character varying(255),
    request_message character varying(500),
    status character varying(255),
    total_price integer NOT NULL,
    user_id character varying(255),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PREPARING'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO ncafe;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: policy_settings; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.policy_settings (
    id bigint NOT NULL,
    is_order_reception_open boolean NOT NULL,
    reward_rate double precision,
    sold_out_handling character varying(255),
    welcome_benefit character varying(255)
);


ALTER TABLE public.policy_settings OWNER TO ncafe;

--
-- Name: policy_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.policy_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.policy_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.reservations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    guest_count integer NOT NULL,
    guest_name character varying(255) NOT NULL,
    guest_phone character varying(255) NOT NULL,
    reserve_date date NOT NULL,
    reserve_time time(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    user_id character varying(255),
    CONSTRAINT reservations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.reservations OWNER TO ncafe;

--
-- Name: reservations_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_settings; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.store_settings (
    id bigint NOT NULL,
    address character varying(255),
    announcement text,
    logo_url character varying(255),
    name character varying(255),
    operating_hours text,
    phone_number character varying(255)
);


ALTER TABLE public.store_settings OWNER TO ncafe;

--
-- Name: store_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: ncafe
--

ALTER TABLE public.store_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: ncafe
--

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    nickname character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO ncafe;

--
-- Name: inyeon_cards id; Type: DEFAULT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.inyeon_cards ALTER COLUMN id SET DEFAULT nextval('public.inyeon_cards_id_seq'::regclass);


--
-- Name: knowledge id; Type: DEFAULT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.knowledge ALTER COLUMN id SET DEFAULT nextval('public.knowledge_id_seq'::regclass);


--
-- Name: matches id; Type: DEFAULT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.matches ALTER COLUMN id SET DEFAULT nextval('public.matches_id_seq'::regclass);


--
-- Data for Name: cart_item_options; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.cart_item_options (id, menu_option_id, name, price, value, cart_item_id) FROM stdin;
7	6	포장 선택	500	박스 포장	7
\.


--
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.cart_items (id, base_price, cart_id, menu_id, menu_name, quantity, total_price) FROM stdin;
7	4000	guest_1773417310168	5	초콜릿 무스	1	4500
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.categories (id, icon, name, sort_order) FROM stdin;
1	🍵	전통차	1
2	🥪	샌드위치&브런치	4
3	🍰	디저트	2
4	🎁	기획 상품	7
5	☕	커피&음료	3
6	🍦	아이스크림&빙수	6
7	🥤	에이드&스무디	5
\.


--
-- Data for Name: inyeon_cards; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.inyeon_cards (id, user_id, interests, mood, greeting, is_active, created_at, updated_at) FROM stdin;
1	mock_user_1	{개발,음악}	설렘	안녕하세요! 코딩하는 아씨입니다.	t	2026-03-13 16:31:13.231873	2026-03-13 16:31:13.231873
2	mock_user_2	{영화,여행}	여유	여행을 좋아하는 선비입니다.	t	2026-03-13 16:31:13.231873	2026-03-13 16:31:13.231873
\.


--
-- Data for Name: knowledge; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.knowledge (id, content, embedding) FROM stdin;
11	엔카페의 정기 영업시간은 매일 오전 10시부터 오후 9시까지입니다. 단, 음료 주문은 마감 30분 전인 오후 8시 30분까지만 가능하며, 브런치 메뉴는 재료 준비를 위해 오후 4시에 주문을 마감합니다	[-0.0016803764,-0.044558093,-0.028850794,-0.03806244,0.0888465,0.014235037,-0.020612082,0.06184691,0.10795316,0.047590517,0.025306938,0.033872824,0.12120592,-0.009297981,-0.009189619,0.003961484,0.03322085,-0.05008915,-0.012771547,-0.044215698,-0.009943755,0.015381196,-0.035921626,0.062197104,0.057868585,0.032620825,-0.004123393,0.012741211,0.06505487,-0.12987584,-0.05122253,-0.0913302,0.0012309379,-0.05176916,0.034659937,0.041124634,-0.048207443,-0.08015168,0.07978919,-0.09372487,0.017656198,0.019455792,0.038905784,0.08986293,0.034747783,0.11531315,-0.052092806,0.103101715,-0.040420238,-0.03200016,-0.068967536,0.055756755,0.037594296,0.06947432,0.01628418,0.0069946987,-0.016788721,-0.036974497,-0.066743396,0.05278047,0.09060437,0.003925387,0.0024261116,0.0039323727,0.09907344,0.05826079,0.05301341,0.046814628,-0.01922611,-0.031588763,-0.04694214,0.07135241,-0.00022190544,-0.04539887,-0.025726559,0.037999105,0.07645888,-0.06863907,0.0028528129,-0.040525157,-0.05719696,-0.005732535,-0.045025934,-0.0046630744,-0.043153666,0.056759473,0.037332896,-0.048430253,0.06755704,-0.0012108214,0.074459985,0.065211795,-0.037400912,-0.08829902,-0.029596971,-0.057266228,-0.029032486,-0.0096139535,-0.022214651,-0.028616354,0.054089427,-0.0837574,0.047782928,-0.030426033,-0.02758566,0.02688194,0.02370738,0.0013138895,0.04203898,-0.06284155,-0.10608518,0.025691142,0.044291902,0.040484674,-0.08017378,0.01929133,0.013183763,-0.040111568,0.019657377,-0.053865414,0.0063263513,-0.050425276,-0.06874306,-0.012695964,-0.030960025,-0.03250661,-0.00401212,0.05958199,-0.07913565,0.030224565,0.040290337,0.0231423,0.047580283,0.03190815,0.0201555,0.032211892,-0.021728115,0.03257364,-0.029354205,-0.057804827,-0.019962188,0.034175564,-0.054453004,0.0794927,0.105399005,0.0738883,0.109359995,-0.057923935,0.12570558,-0.07553529,0.05089704,-0.00039638506,0.09242372,0.07426752,-0.039297633,-0.05468328,-0.056882724,-0.0032875054,-0.00800889,0.0274917,-0.096627906,-0.0973989,-0.108255014,-0.056404058,-0.020675186,-0.06689442,0.041267946,0.10976931,-1.0551194e-05,-0.021960882,-0.07236835,0.062750265,-0.086711146,0.040723525,0.01881714,0.02745104,-0.041731093,0.053544514,0.0885453,0.020929165,-0.02554705,-0.06483618,-0.017769791,-0.069522165,-0.06661573,0.00045892983,-0.056045465,0.023900565,0.0016220128,-0.029860724,0.018818827,0.046863567,-0.040564116,-0.04548126,-0.01762661,0.011995536,-0.084252104,0.039783083,0.03227247,0.0036743127,-0.055866238,-0.09031481,0.06852359,0.0640433,0.016650913,-0.030864902,-0.056984276,0.07881079,-0.062117234,0.05221126,-0.0042297803,-0.028131826,-0.06897449,0.049585745,0.020578718,0.03523263,-0.028233917,0.040025894,-0.087789744,0.030216588,0.036580972,0.004160892,-0.007328813,-0.07385664,-0.054831333,0.03337843,-0.0026370136,-0.09187086,-0.014535381,0.030633312,-0.04106735,-0.043445986,-0.06640902,-0.040788837,-0.028633848,-0.03631846,0.033819664,0.028483776,0.03656797,-0.04768759,-0.06543156,-0.012256775,0.08145635,-0.052840877,0.06665734,-0.014303795,-0.021960368,0.030217944,0.0028486373,0.044063017,0.0052143885,-0.044786036,-0.06160615,-0.0622621,0.060731884,0.036912486,0.03232504,0.08230203,-0.09433293,0.015144113,0.019193664,-0.021790072,0.13742864,0.012431073,0.03799049,-0.047272407,-0.08154578,8.237309e-05,-0.038957883,-0.04257719,-0.08847572,0.025605313,0.061166685,-0.049092762,-0.0529737,-0.0006489686,0.074306525,0.07434675,-0.029762454,-0.042629354,0.045940634,-0.00015843529,0.09320609,0.07404324,0.0026057637,-0.043345433,-0.020091599,0.07925759,-0.013319821,-0.045243744,-0.03270775,-0.025029983,0.10182324,-0.046593536,0.027343223,0.03912244,0.0037609194,0.073628336,-0.031377304,0.005533092,0.005419287,0.004724978,-0.009105692,0.0139721455,-0.06352268,-0.010438143,-0.01369921,0.06210279,0.0107497005,-0.015394565,0.055621292,0.006213603,-0.05490531,-0.06990975,0.04226384,0.04861857,0.018631777,0.04936981,-0.053679507,-0.0367459,-0.0838974,-0.0402209,-0.03844668,-0.025347397,-0.0031386013,0.011120385,-0.07811282,-0.038858056,-0.0056736576,-0.020313049,0.034647424,-0.049620304,-0.013464514,0.08190768,0.01352206,-0.025064187,-0.071699224,0.00044944588,-0.04861843,-0.04364395,0.027739406,-0.00832207,0.011328859,0.063197665,-0.036681924,-0.0355752,0.033319566,0.0038738193,-0.06571631,0.06928852,-0.004391092,-0.08803958,0.02150505,0.055150587,0.03142954,0.020884644,-0.012937377,-0.04378991,0.07505668,0.021220487,0.0060851807,-0.0059515326,-0.008164057,0.06531709,0.07461732,0.025533957,-0.01423806,-0.027367236,-0.017443497,-0.040751655,0.058249116,0.08717757,-0.039635282,-0.0050586443,0.011327394,-0.06929658,-0.013775356,0.004532566,-0.07069413,-0.043732576,0.048988994,0.08838158,0.0172726,0.04312131]
12	반려견 동반은 야외 테라스 좌석에서만 가능하며, 실내 입장은 제한됩니다. 다만, 비가 오거나 눈이 오는 날에는 안전과 청결을 위해 야외 테라스 운영을 중단하므로 반려견과 함께 방문하실 수 없습니다.	[0.026711952,-0.026156401,0.009242302,-0.06477081,0.11543189,-0.022707935,0.027359372,0.029073423,0.036140516,0.034349766,0.065663345,0.054547716,0.048067715,0.009832814,-0.038595054,0.009198536,0.04951825,-0.069898635,-0.043840937,-0.025884397,-0.026105924,-0.041311234,-0.08120043,0.06467344,0.07511378,0.044577815,-0.029828956,-0.00017405911,0.08901957,-0.05955709,-0.02668251,-0.08317149,-0.025694557,-0.05353369,0.052038062,0.044484235,-0.0062459796,-0.012357249,0.0028872283,-0.086967535,0.020712553,0.06197251,0.05913505,0.092044346,0.039452404,0.08330703,-0.0141468765,0.076672636,-0.030376274,-0.048834868,-0.070454724,0.05299722,0.037955567,0.06317011,0.02489434,-0.07603056,-0.013758472,-0.027509721,-0.069587484,0.09073793,0.103606336,-0.013592381,0.05700607,-0.027077843,0.061204046,0.052448004,0.034734994,0.03844991,-0.012132898,-0.081341706,-0.045570564,0.035122998,0.026238441,-0.03301577,0.03238002,-0.019931657,0.08470931,0.013604095,0.04040833,-0.032865282,-0.052221857,-0.061644226,-0.0759557,0.041562505,-0.040062007,0.046064686,0.010736723,-0.06440965,0.05280789,-0.028588325,0.0692498,0.04315505,-0.042855535,-0.04870016,-0.042833634,-0.07632043,-0.043074034,0.025718722,0.024193773,-0.056327976,0.06449062,-0.08892131,0.023714595,-0.038851168,-0.044126987,-0.016979937,0.08023141,-0.018253967,0.053055212,-0.04921431,-0.015439591,0.025228955,0.034487303,0.057090566,-0.12147084,-0.028273288,0.06085478,-0.036774416,0.028889142,-0.079999164,0.0356207,-0.059323624,-0.0583363,-0.0824913,-0.053098068,-0.03756572,0.009175729,0.041110437,-0.013101769,0.0487692,0.028240995,0.057750605,0.059614055,0.07160901,0.037193965,0.08905796,-0.082763635,0.058682423,-0.06610401,-0.016073821,-0.01258688,0.027322326,-0.016542533,0.09561168,0.06668988,0.038211066,0.07836906,-0.03374552,0.10840195,-0.055860326,0.047521222,-0.07685956,0.06968463,0.03809862,0.01216464,-0.009202669,-0.05722365,-0.05398321,0.060410906,0.058537174,-0.04251055,-0.019206444,-0.15160522,-0.049815737,0.0008038137,-0.060756005,0.07523565,0.050044,-0.06287982,0.0031822894,-0.061967753,0.01616821,-0.0133045195,0.071214885,0.00036677244,0.062358998,-0.05740411,0.04403655,0.03972107,0.023271652,0.0028364467,-0.0064972653,-0.04948707,-0.068009354,-0.031133518,-0.0011996115,-0.10098208,-0.0010909621,0.03936864,-0.017581042,-0.0474947,0.008292462,-0.0437368,-0.0491149,0.00032766393,-0.009486029,-0.09475196,0.048242267,0.0320655,0.022456001,-0.00020694011,-0.07341108,0.05345037,0.060151987,-0.022871058,-0.024191031,-0.049457505,0.05714617,-0.07121081,0.05034045,0.022392891,-0.010907813,-0.11697654,0.06354262,-0.051808,0.02631655,-0.0035013685,0.08072625,-0.06384481,0.0022693085,0.049056556,-0.010674774,-0.0045507196,-0.11161507,-0.0023256445,0.03226172,0.06607932,-0.06618861,0.008962968,0.027559832,-0.037751153,0.005192018,-0.01801386,-0.072093554,-0.046801448,-0.061627634,0.021027926,0.035865884,0.04852817,-0.06745034,-0.041396078,-0.011618501,0.049104795,-0.1030652,0.026079284,-0.022751262,-0.022829419,0.02704254,-0.049560945,0.02285838,0.031134767,-0.068260066,-0.079063326,-0.0968914,-0.015486158,0.02372729,0.04650016,0.08618573,-0.047009993,0.03556148,0.0073277038,-0.03384273,0.0909644,0.02603137,0.04573149,-0.06065471,-0.094758585,0.030546173,-0.024336807,-0.023028444,-0.021689774,0.04135553,0.049338583,-0.045206152,-0.049158428,-0.05440457,0.014143795,0.04050116,-0.06666258,-0.021123482,-0.005933558,0.011596526,0.088411435,0.065340884,0.0031581493,-0.049471553,-0.0427087,0.0668184,0.01200712,0.011529516,-0.058092657,-0.017906677,0.0874012,-0.054412525,0.08122963,0.023393922,0.03639631,0.0941981,-0.0478804,0.067717955,-0.02535239,-0.05166842,-0.02839375,0.0073354198,-0.0930795,0.039198317,0.032464962,0.009426122,0.021053497,0.052177172,0.07749605,0.0645961,-0.09564421,-0.051659163,0.058279578,0.030400936,-0.02437813,0.106256425,-0.073952876,-0.05169539,-0.022240164,-0.037773922,-0.007834718,-0.010703893,0.03541086,-0.024117108,-0.023548076,0.0018853424,0.0021964498,0.03649194,0.009205149,-0.020990508,-0.013101294,0.051480733,-0.02890454,0.0009771762,-0.094840005,0.069213465,0.0065545556,-0.011643392,0.043666627,-0.033462826,-0.07385842,-0.0048185145,-0.041828807,-0.05570254,0.025668817,-0.033723142,-0.04834005,0.041593067,0.022577422,-0.08327876,0.042716574,0.060302183,-0.019319173,0.03447174,-0.037091736,-0.06267002,0.050010525,0.01891804,-0.048727624,0.006439817,0.014340755,0.012716509,0.049954105,0.07859672,0.018555446,-0.0061127096,0.01496575,-0.0073091616,0.04758776,0.06957267,-0.029155748,-0.024668744,-0.015666293,-0.052213732,-0.06785736,0.023169173,-0.04691747,-0.054120876,0.038282692,0.06942692,0.03954224,0.03319907]
13	카페 건물 뒤편에 전용 주차장이 마련되어 있습니다. 카페 이용 고객은 1시간 무료 주차가 가능하며, 3만 원 이상 결제 시 추가로 1시간 더(총 2시간) 무료 주차 혜택을 드립니다. 이후에는 10분당 1,000원의 요금이 발생합니다.	[0.0051292954,-0.039645597,-0.029042289,-0.023833916,0.09502741,0.017368795,-0.020438183,0.05385231,0.04630854,0.034641664,0.00026443042,0.01521164,0.06741935,0.0030844372,-0.037757806,0.051595133,0.08894654,-0.017958837,-0.040264085,-0.050528873,0.017857878,-0.011805545,-0.07405194,0.067892514,0.07707121,0.053304642,-0.003027751,0.054688912,0.061935134,-0.09851048,-0.060150582,-0.06696233,-0.010631569,-0.03621028,0.075306445,0.04612427,0.0034768453,-0.08780422,0.033929694,-0.1065719,-0.004324314,0.02062102,0.044627342,0.12674826,0.020018602,0.06703623,-0.029190894,0.08497056,-0.051600497,-0.023135247,-0.04444235,0.064567305,0.027632797,0.060543727,0.02566283,0.00017621893,-0.014850272,-0.055654313,-0.050643127,0.023717739,0.050024346,0.0016127735,0.004294561,-0.021645637,0.09289022,0.10007801,0.04936768,0.046772573,-0.0108775245,-0.03460168,-0.04689697,0.018639026,0.004643954,-0.048916563,0.0030466686,-0.0072536464,0.04895897,-0.016065897,0.055557188,-0.060148936,-0.10408647,-0.019020876,-0.07760483,0.005719762,-0.021912338,0.04197433,0.064435765,-0.08197255,0.016023023,0.018733058,0.098634794,0.085128434,-0.03758685,-0.065088876,-0.039614685,-0.043639388,-0.033244673,0.0127394935,0.016008485,-0.023875901,0.09136898,-0.06451831,0.012400147,-0.0038283197,-0.025816452,-0.012123152,0.04752164,-0.0306369,0.046137802,-0.0665762,-0.07824633,0.042295482,0.07840459,0.023845717,-0.071405016,0.023716705,0.041083623,-0.050330587,0.02208775,-0.037866455,0.018422587,-0.0067195613,-0.069612645,-0.026331611,-0.04226173,0.01626133,0.021975704,0.07090897,-0.091401555,0.045085214,0.026612977,0.06679158,0.07583654,0.07830586,0.07299141,0.06800332,-0.04676557,0.025981562,-0.07646335,-0.016539961,-0.0009010926,0.039800003,-0.03584324,0.08299866,0.057363916,0.05946436,0.10726513,-0.047545347,0.071503766,-0.057742428,0.03737971,-0.096580304,0.023534307,0.052036647,-0.0044247014,-0.09248432,-0.046351083,-0.04365719,-0.004752974,0.02674325,-0.09479896,-0.04764475,-0.092108436,-0.07007314,-0.022235341,-0.06844042,0.03853484,0.0749713,-0.037205704,-0.045998663,-0.041493613,0.034627922,-0.020225462,0.046497904,0.027081853,0.063968785,-0.0811076,0.05044072,0.04529211,0.01349931,0.023441978,-0.044371083,-0.07220432,-0.0805437,-0.08406399,0.022284243,-0.06169495,-0.0068571772,-0.037282795,-0.015769128,-0.02954228,0.03641653,-0.039696336,-0.0856889,-0.014486975,-0.047202576,-0.09873329,0.029377976,0.05076457,0.02064969,-0.03277827,-0.096702114,0.0109096505,0.071217395,-0.019028967,-0.029664608,-0.027658144,0.08212381,-0.1150728,0.03194088,0.01923461,0.005342734,-0.10355405,0.039460927,0.034257278,0.029477106,0.0057030483,0.043114934,-0.038890637,0.029189697,0.048169844,-0.01737587,0.0041622347,-0.12449901,-0.047331624,0.0359326,0.0041592475,-0.09311707,-0.026365152,0.03122279,-0.05881398,-0.034627244,-0.055773925,-0.08727106,-0.031888433,-0.06482699,0.008122525,0.06621392,0.071001194,-0.047809254,-0.06102336,0.011288799,0.049838167,-0.087431155,0.039146997,0.030865565,-0.030928012,0.05637562,0.008270585,0.03451246,0.023639519,-0.079176515,-0.013567921,-0.06744458,-0.014842253,0.007909371,0.013684564,0.07491822,-0.07880387,0.014372213,0.03669769,-0.01835139,0.089199975,0.04168789,0.029753942,-0.028572576,-0.0661102,0.0067583243,-0.008208885,-0.015821707,-0.045043867,0.026068486,0.050127286,-0.05238088,-0.057359643,-0.06908164,0.03728853,0.09154304,-0.01212476,-0.046102636,0.029334206,0.029009502,0.07211829,0.08588767,0.0046444754,-0.019050792,-0.016644547,0.08323559,-0.00939383,-0.0054535796,-0.043174952,-0.03311792,0.072941564,-0.043696627,0.039740603,0.03650185,0.048900153,0.08050123,-0.052013375,0.07074728,-0.04076206,-0.008399573,0.017138204,0.014660982,-0.07677269,0.017332327,-0.037276186,0.06360918,-0.0034423724,0.014905382,0.09098289,0.010365709,-0.04081665,-0.050903656,0.04044832,0.056967042,-0.01938111,0.046130706,-0.04818376,-0.047866046,-0.06335979,-0.049141202,-0.01760522,-0.064201385,0.016810447,-0.011804009,-0.033409007,-0.021704875,0.0083444035,-0.011720912,0.008923477,-0.019150808,-0.022283277,0.02540855,-0.03897467,-0.023284668,-0.11093069,0.04866479,-0.013893765,-0.041988034,0.04817197,0.040392216,-0.038466852,0.017816518,-0.03639249,-0.025545655,0.016376276,0.012844264,-0.030478789,0.03634536,0.063077435,-0.09530117,0.027106652,0.047411244,-0.013268903,0.06396169,-0.076845475,-0.05697128,0.0279417,0.054801214,0.01999507,-0.03824155,0.004162789,0.049398582,0.07293223,0.067275494,0.028126637,-0.023474617,0.0065760524,-0.07502711,0.060094483,0.06756073,-0.069416165,-0.032959342,-0.008824452,-0.06686166,0.0028958982,0.042000283,-0.005401908,-0.025148047,0.08310634,0.08360631,0.03263479,0.04604569]
14	우리 카페는 2층 공간에 한해 노키즈존(13세 미만 입장 제한)으로 운영됩니다. 매주 월요일 오전에는 지역 주민들을 위한 독서 모임 대관이 있어 2층 이용이 12시까지 제한되오니 방문 시 참고 부탁드립니다.	[0.03694004,0.0023092884,-0.036684845,-0.06432817,0.11855732,-0.016837223,0.0017509471,0.036471963,0.06066842,0.02155948,0.06269623,0.012288055,0.085878246,-0.0146459,-0.031585805,0.0024450498,0.05630347,-0.015035753,-0.0360713,-0.043141488,0.012856989,-0.012817605,-0.051468685,0.08955851,0.08123657,0.064922504,0.00921034,0.05077608,0.060576607,-0.08645371,-0.048929427,-0.05792684,-0.00589526,-0.017508822,0.04707035,0.048948042,-0.047663793,-0.06635309,0.045619693,-0.066868715,-0.0045120316,0.046151206,0.047773656,0.09281558,0.053139288,0.0848577,-0.05806895,0.10430291,-0.056478318,-0.037001517,-0.052401997,0.03478096,0.023281928,0.087357976,0.03940755,0.0043341066,-0.021848097,-0.04603113,-0.04814747,0.06383558,0.049766872,0.009408216,0.012917816,0.00042016667,0.10236777,0.08336188,0.001884245,0.03142828,-0.025772443,-0.040875293,-0.019490346,0.046891328,-0.014769449,-0.024173507,0.005536745,0.025105009,0.049529847,-0.004443762,0.060968745,-0.036582388,-0.06565097,-0.0017320554,-0.0856888,0.036129776,-0.027963124,0.09290974,0.029431893,-0.054252744,0.056775145,-0.039774008,0.06702888,0.029760854,-0.07066456,-0.079048164,-0.036179855,-0.011795758,-0.03475032,-0.01166594,0.036279947,-0.04609786,0.06632842,-0.07296508,0.034397714,-0.043843776,-0.07469814,0.034747496,0.047074832,-0.0011569012,0.046467487,-0.056142233,-0.07764951,0.07107897,0.024544368,0.025565475,-0.045481104,-0.012784323,0.014831607,-0.08804696,0.05004379,-0.031026486,0.024223117,-0.027437527,-0.043538764,-0.02177395,-0.051446747,0.005974663,0.016049068,0.038008366,-0.008083109,0.05482731,0.03526706,0.043395422,0.023065357,0.0554495,0.071115896,0.05333169,-0.092430696,0.037019074,-0.05524313,0.015074138,0.007992652,0.0758575,-0.04377523,0.07239501,0.05919482,0.08001453,0.08054713,-0.051226888,0.10964412,-0.021780992,0.027434137,-0.0781426,0.053281322,0.038847532,-0.008494095,-0.05030741,-0.023701519,-0.048107658,0.040064327,0.07439153,-0.082917854,-0.03243171,-0.117863275,-0.1005348,-0.03630711,-0.070002645,0.049286492,0.06371461,-0.036374528,-0.004453928,-0.027514918,-0.0133080315,-0.054960325,0.05516563,-0.00068981946,0.10242736,-0.076874554,0.051793523,0.072575755,0.056525208,-0.008252216,-0.019871235,-0.051735677,-0.07657461,-0.030824348,-0.018713146,-0.06178033,0.0328387,0.009884557,-0.038403217,-0.03296695,0.03244268,-0.05599155,-0.034029152,-0.024864528,-0.03556256,-0.058218215,0.03709476,0.054216553,0.038762353,-0.015138086,-0.058067717,0.028848799,0.07475914,-0.06131269,-0.038710367,-0.082014576,0.042005323,-0.06057756,0.052874614,0.04255901,0.014673147,-0.07640637,0.051045507,0.012449037,-0.008176032,-0.009911819,0.016198415,-0.082405984,0.04101366,0.039047953,-0.02439772,-0.011284896,-0.110726446,-0.024241462,0.04397727,0.04057557,-0.08009812,-0.02478106,0.0041395556,-0.037386786,-0.014126407,-0.052513804,-0.04761188,-0.04150757,-0.04431624,0.03032802,0.04752068,0.071107,-0.07470211,-0.07270126,0.0050307275,0.021306664,-0.09262524,0.039957523,0.006313899,-0.013224239,0.029466324,-0.019783929,0.0110004945,0.03348211,-0.047027756,-0.05123085,-0.10251054,0.015943812,-0.006450946,0.06809429,0.05678374,-0.11902064,0.019331412,-0.019480996,-0.025650728,0.114450544,0.018157283,0.028793598,-0.040639445,-0.09650672,0.016861144,-0.038312066,-0.02919537,-0.056261215,0.04230569,0.023014808,-0.06593513,-0.055406652,-0.051041238,0.05420532,0.06678943,-0.035090618,-0.03965251,-0.018294727,0.016963646,0.046084967,0.077118345,0.023154136,-0.026085561,0.0030952836,0.08487041,0.028670143,-0.009688078,-0.059682623,-0.037494626,0.05120413,-0.05064037,0.074439,0.025358865,0.016519845,0.08034228,-0.055896744,0.059760083,-0.06529967,-0.0247762,-0.013346558,0.003480664,-0.06782807,-0.0019819147,-0.026204597,0.06327026,0.0055801184,0.043439202,0.08331486,-0.013518376,-0.08120842,-0.040979676,0.075995795,0.008179623,-0.025542486,0.03318445,-0.07947926,-0.021277586,-0.11956875,-0.057281595,-0.014176035,-0.05224344,0.032407705,-0.0013447884,-0.068647765,-0.050413392,0.0069640134,-0.015440553,0.038784605,-0.02224245,-0.010737481,0.061141178,-0.034090023,-0.010711162,-0.11177592,0.011311276,-0.020981515,-0.0041008387,0.024252709,0.0016566984,-0.019598871,0.035405368,-0.03376783,-0.039068058,-0.005172552,-0.016466105,-0.06273268,0.079509266,0.0017611668,-0.111904696,0.022975678,0.062590845,0.0012759734,0.066253565,-0.029799841,-0.015003236,0.046080556,0.052697644,-0.031669207,-0.015807873,0.0122874975,0.06083716,0.05680342,0.051860902,-0.015489227,-0.038284153,0.05717873,-0.07076212,0.041436717,0.10597606,-0.07104162,-0.056363624,0.018656818,-0.049053207,-0.06293067,0.018501058,-0.04120692,-0.03579518,0.078808546,0.059852708,0.06399523,0.05321944]
\.


--
-- Data for Name: matches; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.matches (id, requester_id, receiver_id, match_score, status, ai_message, created_at, responded_at) FROM stdin;
\.


--
-- Data for Name: menu_curation_tags; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.menu_curation_tags (menu_id, tag) FROM stdin;
30	MZ인기메뉴
30	이달의 신메뉴
32	월화선생 추천
32	이달의 신메뉴
34	계절메뉴
\.


--
-- Data for Name: menu_images; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.menu_images (id, alt_text, menu_id, sort_order, src_url) FROM stdin;
1	햄 치즈 샌드위치 이미지	1	1	/images/ham-cheese-sandwich.png
2	베이글 크림 치즈 이미지	2	1	/images/bagel-cream-cheese.png
3	스크램블 에그 샌드위치 이미지	3	1	/images/scrambled-egg-sandwich.png
4	두바이 쫀득 쿠키 이미지	4	1	/images/dubai-zzondeuk-cookie.png
5	초콜릿 무스 이미지	5	1	/images/chocolate-mousse.png
6	초콜릿 크로와상 이미지	6	1	/images/chocolate-croissant.png
7	초코칩 쿠키 이미지	7	1	/images/choco-chip-cookie.png
8	버터 쿠키 이미지	8	1	/images/butter-cookie.png
9	아몬드 쿠키 이미지	9	1	/images/almond-cookie.png
10	바나나 라떼 이미지	10	1	/images/bananalatte.png
11	에스프레소 이미지	11	1	/images/espresso.png
12	아메리카노 이미지	12	1	/images/americano.png
13	카페 라떼 이미지	13	1	/images/cafelatte.png
14	카라멜 마키아또 이미지	14	1	/images/caramel-macchiato.png
15	카푸치노 이미지	15	1	/images/capuchino.png
16	명품 대추차 상세 이미지	16	1	/images/jujube-tea.png
17	인절미 토스트 상세 이미지	17	1	/images/injeolmi-toast.png
18	흑임자 크림 라떼 상세 이미지	18	1	/images/black-sesame.png
19	수제 얼음 식혜 상세 이미지	19	1	/images/sikhye.png
20	약과 휘낭시에 상세 이미지	20	1	/images/yakgwa-fin.png
21	잠봉뵈르 샌드위치 이미지	21	1	/images/jambon-beurre.png
22	아보카도 에그 토스트 이미지	22	1	/images/avocado-egg-toast.png
23	궁중 쌍화차 이미지	23	1	/images/ssanghwa-cha.png
24	도라지 배차 이미지	24	1	/images/balloon-flower-pear-tea.png
25	샤인머스캣 에이드 이미지	25	1	/images/shine-muscat-ade.png
26	자몽 허니 블랙티 이미지	26	1	/images/grapefruit-honey-black-tea.png
27	쑥 인절미 마카롱 이미지	27	1	/images/mugwort-injeolmi-macaron.png
28	홍시 수정과 소르베 이미지	28	1	/images/persimmon-sorbet.png
29	햄 치즈 샌드위치 상세 이미지	1	2	/images/ham-cheese-sandwich1.png
30	베이글 크림 치즈 상세 이미지	2	2	/images/bagel-cream-cheese1.png
31	스크램블 에그 샌드위치 상세 이미지	3	2	/images/scrambled-egg-sandwich1.png
32	두바이 쫀득 쿠키 상세 이미지	4	2	/images/dubai-zzondeuk-cookie1.png
33	초콜릿 무스 상세 이미지	5	2	/images/chocolate-mousse1.png
34	초콜릿 크로와상 상세 이미지	6	2	/images/chocolate- croissant1.png
35	초코칩 쿠키 상세 이미지	7	2	/images/choco-chip-cookie1.png
36	버터 쿠키 상세 이미지	8	2	/images/butter-cookie1.png
37	아몬드 쿠키 상세 이미지	9	2	/images/almond-cookie1.png
38	바나나 라떼 상세 이미지	10	2	/images/bananalatte1.png
39	에스프레소 상세 이미지	11	2	/images/espresso1.png
40	아메리카노 상세 이미지	12	2	/images/americano1.png
41	카페 라떼 상세 이미지	13	2	/images/cafelatte1.png
42	카라멜 마키아또 상세 이미지	14	2	/images/caramel-macchiato1.png
43	카푸치노 상세 이미지	15	2	/images/capuchino1.png
49	\N	30	1	/images/41912b89-c19c-4b82-85ba-1b4333867ace.png
50	쑥 크림 라떼	32	1	/images/575a0b6f-1aad-4d5c-ae80-2085c89e8f25.png
51	오미자 베리 에이드	34	1	/images/02e6382f-8067-4965-9533-9e1845dce7da.png
\.


--
-- Data for Name: menu_option_mapping; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.menu_option_mapping (menu_id, option_id) FROM stdin;
27	5
3	5
34	7
34	8
\.


--
-- Data for Name: menu_options; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.menu_options (id, name, price, value) FROM stdin;
1	추가 선택	500	샷 추가
2	추가 선택	500	휘핑 추가
3	추가 선택	500	시럽 추가
4	온도	0	ICE
5	포장 선택	0	매장 취식
6	포장 선택	500	박스 포장
7	사이즈	0	Regular
8	사이즈	1000	Large
9	온도	0	HOT
\.


--
-- Data for Name: menus; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.menus (id, admin_memo, alt_text, category_id, cost_price, created_at, description, eng_name, is_available, kor_name, price, slug, updated_at, allergy_info, sort_order) FROM stdin;
30			1	\N	2026-03-14 09:54:49.552223	테스트입니다.	test	t	테스트	5000	test	2026-03-14 12:10:17.175104	\N	1
28		홍시 수정과 소르베	6	\N	2026-03-13 15:14:00.652205	홍시 소르베 위에 수정과 소스	persimmon sorbet with sujeonggwa	t	홍시 수정과 소르베	7200	persimmon-sorbet-with-sujeonggwa	2026-03-13 15:14:00.652205		4
27		쑥 인절미 마카롱	3	\N	2026-03-13 15:14:00.652205	쑥 향과 인절미가 들어간 마카롱	mugwort injeolmi macaron	t	쑥 인절미 마카롱	6000	mugwort-injeolmi-macaron	2026-03-13 15:14:00.652205		5
32		쑥 크림 라떼	5	6000	2026-03-14 12:19:08.285185	어린 쑥의 향긋함과 부드러운 우유 거품이 만나 입안 가득 봄의 기운을 전하는 고소한 라떼	Mugwort Cream Latte	t	쑥 크림 라떼	6500	MugwortCreamLatte	2026-03-14 12:19:08.285196	\N	2
33	테스트용	이미지 준비중	4	\N	2026-03-15 02:02:59.82192	현재 이미지를 준비 중인 메뉴입니다.	Image Pending Menu	t	이미지 준비중 메뉴	3000	image-pending-menu	2026-03-15 02:02:59.82192	없음	3
26		자몽 허니 블랙티	7	\N	2026-03-13 15:14:00.652205	자몽과 꿀이 들어간 블랙티	grapefruit honey black tea	t	자몽 허니 블랙티	6800	grapefruit-honey-black-tea	2026-03-13 15:14:00.652205		6
25		샤인머스캣 에이드	7	\N	2026-03-13 15:14:00.652205	달콤한 샤인머스캣 에이드	shine muscat ade	t	샤인머스캣 에이드	7000	shine-muscat-ade	2026-03-13 15:14:00.652205		7
24	기관지에 좋음	도라지 배차	1	\N	2026-03-13 15:14:00.652205	도라지와 배가 어우러진 차	balloon flower pear tea	t	도라지 배차	5000	balloon-flower-pear-tea	2026-03-13 15:14:00.652205	없음	8
23	중장년층 선호	쌍화차	1	\N	2026-03-13 15:14:00.652205	궁중에서 즐기던 약차	royal ssanghwa tea	t	궁중 쌍화차	5500	royal-ssanghwa-tea	2026-03-13 15:14:00.652205	호두, 땅콩	9
22	조리 간편	아보카도 에그 토스트	2	\N	2026-03-13 15:14:00.652205	신선한 아보카도와 계란 토스트	avocado egg toast	t	아보카도 에그 토스트	8200	avocado-egg-toast	2026-03-13 15:14:00.652205	밀, 계란	10
21	식사대용 인기	잠봉뵈르 샌드위치	2	\N	2026-03-13 15:14:00.652205	프렌치 스타일 햄 버터 샌드위치	jambon-beurre sandwich	t	잠봉뵈르 샌드위치	9000	jambon-beurre-sandwich	2026-03-13 15:14:00.652205	밀, 우유, 돼지고기	11
20	신메뉴 추가	약과 휘낭시에	3	\N	2026-03-13 15:14:00.652205	전통 과자 약과와 프랑스식 휘낭시에	yakgwa financier	t	약과 휘낭시에	8000	yakgwa-financier	2026-03-13 15:14:00.652205	밀, 계란, 우유	12
19	여름 시즌	얼음 식혜	1	\N	2026-03-13 15:14:00.652205	직접 끓인 달콤한 식혜를 얼음과 함께	sikhye with ice	t	수제 얼음 식혜	4500	sikhye-with-ice	2026-03-13 15:14:00.652205	쌀	13
18	MZ세대 타겟	흑임자 크림 라떼	5	\N	2026-03-13 15:14:00.652205	고소한 흑임자 크림 라떼	black sesame latte	t	흑임자 크림 라떼	6500	black-sesame-latte	2026-03-13 15:14:00.652205	우유, 깨	14
17	디저트 베스트	인절미 토스트	3	\N	2026-03-13 15:14:00.652205	쫀득한 인절미가 올라간 토스트	injeolmi toast	t	인절미 토스트	7500	injeolmi-toast	2026-03-13 15:14:00.652205	우유, 밀, 콩	15
16	인기 메뉴	대추차	1	\N	2026-03-13 15:14:00.652205	정성껏 우린 대추차	jujube tea	t	명품 대추차	5000	jujube-tea	2026-03-13 15:14:00.652205	대추	16
15	기본 메뉴	카푸치노	5	\N	2026-03-13 15:14:00.652205	부드러운 우유 거품과 에스프레소의 조화	Cappuccino	t	카푸치노	5000	cappuccino	2026-03-13 15:14:00.652205	우유	17
14	기본 메뉴	카라멜 마키아또	5	\N	2026-03-13 15:14:00.652205	달콤한 카라멜 시럽과 에스프레소의 조화	Caramel Macchiato	t	카라멜 마키아또	5500	caramel-macchiato	2026-03-13 15:14:00.652205	우유, 대두	18
13	기본 메뉴	카페 라떼	5	\N	2026-03-13 15:14:00.652205	부드러운 우유와 에스프레소의 조화	Caffè Latte	t	카페 라떼	5000	caffè-latte	2026-03-13 15:14:00.652205	우유	19
12	기본 메뉴	아메리카노	5	\N	2026-03-13 15:14:00.652205	진한 에스프레소와 물의 조화	Americano	t	아메리카노	4500	americano	2026-03-13 15:14:00.652205	없음	20
11	기본 메뉴	에스프레소	5	\N	2026-03-13 15:14:00.652205	espresso	espresso	t	에스프레소	3500	espresso	2026-03-13 15:14:00.652205	없음	21
10	기본 메뉴	바나나 라떼	5	\N	2026-03-13 15:14:00.652205	바나나와 우유가 들어간 라떼	banana latte	t	바나나 라떼	5000	banana-latte	2026-03-13 15:14:00.652205	우유	22
9	기본 메뉴	아몬드 쿠키	3	\N	2026-03-13 15:14:00.652205	아몬드가 들어간 쿠키	almond cookie	t	아몬드 쿠키	2000	almond-cookie	2026-03-13 15:14:00.652205	밀, 계란, 우유	23
8	기본 메뉴	버터 쿠키	3	\N	2026-03-13 15:14:00.652205	버터가 들어간 쿠키	butter cookie	t	버터 쿠키	2000	butter-cookie	2026-03-13 15:14:00.652205	밀, 계란, 우유	24
7	기본 메뉴	초코칩 쿠키	3	\N	2026-03-13 15:14:00.652205	초코칩이 들어간 쿠키	choco chip cookie	t	초코칩 쿠키	2000	choco-chip-cookie	2026-03-13 15:14:00.652205	밀, 계란, 우유	25
6	기본 메뉴	초콜릿 크로와상	3	\N	2026-03-13 15:14:00.652205	초콜릿이 들어간 크로와상	chocolate croissant	t	초콜릿 크로와상	4000	chocolate-croissant	2026-03-13 15:14:00.652205	밀, 계란, 우유	26
5	기본 메뉴	초콜릿 무스	3	\N	2026-03-13 15:14:00.652205	진한 초콜릿 무스	chocolate mousse	t	초콜릿 무스	4000	chocolate-mousse	2026-03-13 15:14:00.652205	밀, 계란, 우유	27
4	기본 메뉴	두바이 쫀득 쿠키	3	\N	2026-03-13 15:14:00.652205	쫀득한 식감의 쿠키	dubai zzondeuk cookie	t	두바이 쫀득 쿠키	2000	dubai-zzondeuk-cookie	2026-03-13 15:14:00.652205	밀, 계란, 우유	28
3	기본 메뉴	스크램블 에그 샌드위치	2	\N	2026-03-13 15:14:00.652205	스크램블 에그가 들어간 샌드위치	scrambled egg sandwich	t	스크램블 에그 샌드위치	7000	scrambled-egg-sandwich	2026-03-13 15:14:00.652205	밀, 계란, 우유	29
2	기본 메뉴	베이글 크림 치즈	2	\N	2026-03-13 15:14:00.652205	베이글에 크림 치즈를 바른 샌드위치	bagel cream cheese	t	베이글 크림 치즈	5000	bagel-cream-cheese	2026-03-13 15:14:00.652205	밀, 계란, 우유	30
1	기본 메뉴	햄 치즈 샌드위치	2	\N	2026-03-13 15:14:00.652205	햄과 치즈가 들어간 샌드위치	ham cheese sandwich	t	햄 치즈 샌드위치	6000	ham-cheese-sandwich	2026-03-13 15:14:00.652205	밀, 계란, 우유	31
34		오미자 베리 에이드	7	\N	2026-03-15 04:36:44.033963	다섯 가지 맛의 오미자와 상큼한 베리류를 블렌딩하여 청량감을 더한 스파클링 티	Omija Berry Ade	t	오미자 베리 에이드	6000	OmijaBerryAde	2026-03-15 04:38:41.457097	\N	0
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.order_items (id, menu_id, menu_name, options_text, price, quantity, order_id) FROM stdin;
1	4	두바이 쫀득 쿠키	포장 선택: 박스 포장	2500	1	1
2	18	흑임자 크림 라떼		6500	1	2
3	3	스크램블 에그 샌드위치		7000	1	2
4	11	에스프레소	추가 선택: 시럽 추가, 사이즈: Large, 온도: HOT	5000	1	2
5	4	두바이 쫀득 쿠키	포장 선택: 박스 포장	2500	1	3
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.orders (id, approval_number, cart_id, ordered_at, payment_method, request_message, status, total_price, user_id) FROM stdin;
1	APP-80A19C86	guest_1773290410087	2026-03-13 15:37:23.785619	CARD		PENDING	2500	\N
2	APP-8BB4A295	guest_1773417310168	2026-03-13 17:20:20.990449	CARD	뜨겁게	PENDING	18500	\N
3	APP-235AE7C7	user-184afc27-cdc8-4624-94db-edcdc6aa1bba	2026-03-13 17:31:39.300061	CARD		COMPLETED	2500	184afc27-cdc8-4624-94db-edcdc6aa1bba
\.


--
-- Data for Name: policy_settings; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.policy_settings (id, is_order_reception_open, reward_rate, sold_out_handling, welcome_benefit) FROM stdin;
\.


--
-- Data for Name: reservations; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.reservations (id, created_at, guest_count, guest_name, guest_phone, reserve_date, reserve_time, status, user_id) FROM stdin;
1	2026-03-13 15:14:00.952196	2	홍길동	010-1234-5678	2026-03-14	14:00:00	PENDING	\N
2	2026-03-13 15:14:00.952227	4	성춘향	010-9876-5432	2026-03-15	16:00:00	CONFIRMED	\N
3	2026-03-13 15:14:00.952243	1	이몽룡	010-1111-2222	2026-03-16	11:00:00	PENDING	\N
4	2026-03-13 17:23:07.627692	2	jung	010-1111-1111	2026-04-02	15:00:00	CANCELLED	184afc27-cdc8-4624-94db-edcdc6aa1bba
\.


--
-- Data for Name: store_settings; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.store_settings (id, address, announcement, logo_url, name, operating_hours, phone_number) FROM stdin;
1	서울특별시 강남구	엔카페에 추가기능을 원하시면 연락주세요...ㅠ	\N	N-카페	{}	02-123-4567
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: ncafe
--

COPY public.users (id, nickname, password, role) FROM stdin;
184afc27-cdc8-4624-94db-edcdc6aa1bba	jung	$2a$10$Sk4zYJ5lZrLQttE4kM7jD..GW/AcI5A5d6OpKuUjeCes1HZvxQcUC	ROLE_USER
7de46965-0e34-411a-82f9-66d46fb269a7	hong	$2a$10$E0ZR21RtgvjQjxE7mIrXSe2ESKFbA8m/533v0AsKW2OlP6q2GEGeK	ROLE_USER
a8d8b30f-8ff8-4463-b885-8d5dbd71917c	admin	$2a$10$qDCbhqJVsfdwg9ZWZywsOOogF9c8jm6EuDP5wB4BIpW8MzgAbuW..	ROLE_MASTER
\.


--
-- Name: cart_item_options_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.cart_item_options_id_seq', 23, true);


--
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 15, true);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.categories_id_seq', 7, true);


--
-- Name: inyeon_cards_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.inyeon_cards_id_seq', 2, true);


--
-- Name: knowledge_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.knowledge_id_seq', 14, true);


--
-- Name: matches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.matches_id_seq', 1, false);


--
-- Name: menu_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.menu_images_id_seq', 51, true);


--
-- Name: menu_options_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.menu_options_id_seq', 9, true);


--
-- Name: menus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.menus_id_seq', 34, true);


--
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.order_items_id_seq', 5, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.orders_id_seq', 3, true);


--
-- Name: policy_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.policy_settings_id_seq', 1, false);


--
-- Name: reservations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.reservations_id_seq', 4, true);


--
-- Name: store_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ncafe
--

SELECT pg_catalog.setval('public.store_settings_id_seq', 1, true);


--
-- Name: cart_item_options cart_item_options_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.cart_item_options
    ADD CONSTRAINT cart_item_options_pkey PRIMARY KEY (id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: inyeon_cards inyeon_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.inyeon_cards
    ADD CONSTRAINT inyeon_cards_pkey PRIMARY KEY (id);


--
-- Name: inyeon_cards inyeon_cards_user_id_key; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.inyeon_cards
    ADD CONSTRAINT inyeon_cards_user_id_key UNIQUE (user_id);


--
-- Name: knowledge knowledge_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.knowledge
    ADD CONSTRAINT knowledge_pkey PRIMARY KEY (id);


--
-- Name: matches matches_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (id);


--
-- Name: menu_images menu_images_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.menu_images
    ADD CONSTRAINT menu_images_pkey PRIMARY KEY (id);


--
-- Name: menu_option_mapping menu_option_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.menu_option_mapping
    ADD CONSTRAINT menu_option_mapping_pkey PRIMARY KEY (menu_id, option_id);


--
-- Name: menu_options menu_options_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.menu_options
    ADD CONSTRAINT menu_options_pkey PRIMARY KEY (id);


--
-- Name: menus menus_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.menus
    ADD CONSTRAINT menus_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: policy_settings policy_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.policy_settings
    ADD CONSTRAINT policy_settings_pkey PRIMARY KEY (id);


--
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);


--
-- Name: store_settings store_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.store_settings
    ADD CONSTRAINT store_settings_pkey PRIMARY KEY (id);


--
-- Name: users uk2ty1xmrrgtn89xt7kyxx6ta7h; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname);


--
-- Name: menus uk6lq1bpydlfq768ryr3c9f2nig; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.menus
    ADD CONSTRAINT uk6lq1bpydlfq768ryr3c9f2nig UNIQUE (slug);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: ix_inyeon_cards_id; Type: INDEX; Schema: public; Owner: ncafe
--

CREATE INDEX ix_inyeon_cards_id ON public.inyeon_cards USING btree (id);


--
-- Name: ix_knowledge_id; Type: INDEX; Schema: public; Owner: ncafe
--

CREATE INDEX ix_knowledge_id ON public.knowledge USING btree (id);


--
-- Name: ix_matches_id; Type: INDEX; Schema: public; Owner: ncafe
--

CREATE INDEX ix_matches_id ON public.matches USING btree (id);


--
-- Name: menu_option_mapping fk_menu; Type: FK CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.menu_option_mapping
    ADD CONSTRAINT fk_menu FOREIGN KEY (menu_id) REFERENCES public.menus(id) ON DELETE CASCADE;


--
-- Name: menu_option_mapping fk_option; Type: FK CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.menu_option_mapping
    ADD CONSTRAINT fk_option FOREIGN KEY (option_id) REFERENCES public.menu_options(id) ON DELETE CASCADE;


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: menu_curation_tags fklqu8biv0aijb1m0k5mnjal6ty; Type: FK CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.menu_curation_tags
    ADD CONSTRAINT fklqu8biv0aijb1m0k5mnjal6ty FOREIGN KEY (menu_id) REFERENCES public.menus(id);


--
-- Name: cart_item_options fkrkqjsm24carqadm4bamge81vl; Type: FK CONSTRAINT; Schema: public; Owner: ncafe
--

ALTER TABLE ONLY public.cart_item_options
    ADD CONSTRAINT fkrkqjsm24carqadm4bamge81vl FOREIGN KEY (cart_item_id) REFERENCES public.cart_items(id);


--
-- PostgreSQL database dump complete
--

\unrestrict kqNPccL76U9r4Z7hbk7YxnwIOnupR8BoZpCZbJiob4J3un0CPkriJurHGsNOFz4

