spring.application.name=backend
server.port=8081



spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# 테이블 생성 후 data.sql을 실행하도록 설정
spring.sql.init.mode=always
# Hibernate의 테이블 생성 작업이 끝난 뒤에 data.sql이 실행되도록 순서 보장 (Spring Boot 2.5 이상)
spring.jpa.defer-datasource-initialization=true

# 파일 업로드 및 정적 리소스 설정
upload.path=/app/dist/ncafe-upload/
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=file:/app/dist/ncafe-upload/,classpath:/static/

# JWT 설정
jwt.secret=${JWT_SECRET}
jwt.token-validity-in-seconds=86400

# Security Debugging
logging.level.org.springframework.security=DEBUG
logging.level.com.new_cafe.app.backend=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.web=DEBUG
logging.level.org.springframework.web=DEBUG

# Redis 설정
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379