# spring.application.name=backend
# server.port=8012



spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 테이블 생성 후 data.sql을 실행하도록 설정
spring.sql.init.mode=never
# Hibernate의 테이블 생성 작업이 끝난 뒤에 data.sql이 실행되도록 순서 보장 (Spring Boot 2.5 이상)
spring.jpa.defer-datasource-initialization=true

spring.mvc.static-path-pattern=/**
# 파일 업로드 및 정적 리소스 설정
spring.web.resources.static-locations=file:./upload/,classpath:/static/

# JWT 설정
jwt.secret=${JWT_SECRET}
jwt.token-validity-in-seconds=86400